# Generated by Django 4.2.7 on 2025-09-22 20:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplaintAdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(
                        help_text="معرف الشكوى في خدمة الشكاوى",
                        max_length=50,
                        verbose_name="معرف الشكوى",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(
                        help_text="معرف الأدمن الذي قام بالإجراء",
                        max_length=50,
                        verbose_name="معرف الأدمن",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(
                        help_text="اسم الأدمن الذي قام بالإجراء",
                        max_length=100,
                        verbose_name="اسم الأدمن",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("received", "تم الاستلام"),
                            ("reviewed", "تمت المراجعة"),
                            ("assigned", "تم الإسناد"),
                            ("escalated", "تم التصعيد"),
                            ("resolved", "تم الحل"),
                            ("rejected", "تم الرفض"),
                            ("archived", "تم الأرشفة"),
                            ("reopened", "تم إعادة الفتح"),
                        ],
                        help_text="نوع الإجراء المتخذ",
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات الأدمن على الإجراء",
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "assigned_to_representative_id",
                    models.CharField(
                        blank=True,
                        help_text="معرف النائب الذي تم إسناد الشكوى إليه",
                        max_length=50,
                        null=True,
                        verbose_name="معرف النائب المُسند إليه",
                    ),
                ),
                (
                    "assigned_to_representative_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم النائب الذي تم إسناد الشكوى إليه",
                        max_length=100,
                        verbose_name="اسم النائب المُسند إليه",
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="medium",
                        help_text="مستوى أولوية الشكوى",
                        max_length=20,
                        verbose_name="مستوى الأولوية",
                    ),
                ),
                (
                    "expected_resolution_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="التاريخ المتوقع لحل الشكوى",
                        null=True,
                        verbose_name="تاريخ الحل المتوقع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإجراء"
                    ),
                ),
            ],
            options={
                "verbose_name": "إجراء أدمن على الشكوى",
                "verbose_name_plural": "إجراءات الأدمن على الشكاوى",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم تصنيف الشكوى",
                        max_length=100,
                        verbose_name="اسم التصنيف",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="وصف تصنيف الشكوى", verbose_name="الوصف"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="هل التصنيف نشط؟", verbose_name="نشط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تصنيف الشكوى",
                "verbose_name_plural": "تصنيفات الشكاوى",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="معرف فريد لعملية التصدير",
                        unique=True,
                        verbose_name="معرف التصدير",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(
                        help_text="معرف الأدمن الذي طلب التصدير",
                        max_length=50,
                        verbose_name="معرف الأدمن",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(
                        help_text="اسم الأدمن الذي طلب التصدير",
                        max_length=100,
                        verbose_name="اسم الأدمن",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("zip", "ملف مضغوط (ZIP)"),
                            ("excel", "ملف إكسل (XLSX)"),
                            ("pdf", "ملف PDF"),
                            ("csv", "ملف CSV"),
                        ],
                        default="zip",
                        help_text="صيغة ملف التصدير",
                        max_length=10,
                        verbose_name="صيغة التصدير",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الانتظار"),
                            ("processing", "جاري المعالجة"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        help_text="حالة عملية التصدير",
                        max_length=20,
                        verbose_name="حالة التصدير",
                    ),
                ),
                (
                    "filter_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="معايير تصفية الشكاوى للتصدير",
                        verbose_name="معايير التصفية",
                    ),
                ),
                (
                    "total_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى المُصدرة",
                        verbose_name="عدد الشكاوى",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="مسار ملف التصدير",
                        max_length=500,
                        verbose_name="مسار الملف",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0,
                        help_text="حجم ملف التصدير بالبايت",
                        verbose_name="حجم الملف (بايت)",
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        help_text="رابط تحميل ملف التصدير",
                        verbose_name="رابط التحميل",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاريخ انتهاء صلاحية رابط التحميل",
                        null=True,
                        verbose_name="تاريخ انتهاء الصلاحية",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="رسالة الخطأ في حالة فشل التصدير",
                        verbose_name="رسالة الخطأ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاريخ إكمال التصدير",
                        null=True,
                        verbose_name="تاريخ الإكمال",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصدير الشكاوى",
                "verbose_name_plural": "تصديرات الشكاوى",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم قالب الرد",
                        max_length=100,
                        verbose_name="اسم القالب",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("acknowledgment", "إقرار الاستلام"),
                            ("assignment", "إشعار الإسناد"),
                            ("resolution", "إشعار الحل"),
                            ("rejection", "إشعار الرفض"),
                            ("follow_up", "متابعة"),
                            ("closure", "إغلاق الشكوى"),
                        ],
                        help_text="نوع قالب الرد",
                        max_length=20,
                        verbose_name="نوع القالب",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="موضوع رسالة الرد",
                        max_length=200,
                        verbose_name="موضوع الرسالة",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="محتوى قالب الرد (يمكن استخدام متغيرات مثل {citizen_name})",
                        verbose_name="محتوى القالب",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="هل القالب نشط؟", verbose_name="نشط"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="الأدمن الذي أنشأ القالب",
                        max_length=100,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قالب الرد",
                "verbose_name_plural": "قوالب الردود",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="تاريخ الإحصائية",
                        verbose_name="التاريخ",
                    ),
                ),
                (
                    "total_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="إجمالي عدد الشكاوى",
                        verbose_name="إجمالي الشكاوى",
                    ),
                ),
                (
                    "new_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى الجديدة",
                        verbose_name="الشكاوى الجديدة",
                    ),
                ),
                (
                    "assigned_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى المُسندة للنواب",
                        verbose_name="الشكاوى المُسندة",
                    ),
                ),
                (
                    "resolved_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى المحلولة",
                        verbose_name="الشكاوى المحلولة",
                    ),
                ),
                (
                    "rejected_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى المرفوضة",
                        verbose_name="الشكاوى المرفوضة",
                    ),
                ),
                (
                    "pending_complaints",
                    models.IntegerField(
                        default=0,
                        help_text="عدد الشكاوى المعلقة",
                        verbose_name="الشكاوى المعلقة",
                    ),
                ),
                (
                    "average_resolution_time",
                    models.FloatField(
                        default=0.0,
                        help_text="متوسط الوقت المطلوب لحل الشكوى",
                        verbose_name="متوسط وقت الحل (بالأيام)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إحصائية الشكاوى",
                "verbose_name_plural": "إحصائيات الشكاوى",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
