# Generated by Django 4.2.7 on 2025-09-22 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RatingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "representative_id",
                    models.CharField(
                        help_text="معرف النائب في خدمة المحتوى",
                        max_length=50,
                        unique=True,
                        verbose_name="معرف النائب",
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        help_text="اسم النائب",
                        max_length=100,
                        verbose_name="اسم النائب",
                    ),
                ),
                (
                    "default_rating",
                    models.FloatField(
                        default=4.8,
                        help_text="التقييم الافتراضي للنائب (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="التقييم الافتراضي",
                    ),
                ),
                (
                    "default_voters_count",
                    models.IntegerField(
                        default=4000,
                        help_text="عدد المقيمين الافتراضي",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد المقيمين الافتراضي",
                    ),
                ),
                (
                    "show_real_rating",
                    models.BooleanField(
                        default=False,
                        help_text="إظهار التقييم الحقيقي أم الافتراضي",
                        verbose_name="إظهار التقييم الحقيقي",
                    ),
                ),
                (
                    "is_rating_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="هل التقييم مفعل لهذا النائب؟",
                        verbose_name="تفعيل التقييم",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات التقييم",
                "verbose_name_plural": "إعدادات التقييمات",
                "ordering": ["representative_name"],
            },
        ),
        migrations.CreateModel(
            name="VisitorCounterConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_random_visitors",
                    models.IntegerField(
                        default=1000,
                        help_text="الحد الأدنى للرقم العشوائي للزوار",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الحد الأدنى للزوار العشوائيين",
                    ),
                ),
                (
                    "max_random_visitors",
                    models.IntegerField(
                        default=1500,
                        help_text="الحد الأقصى للرقم العشوائي للزوار",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الحد الأقصى للزوار العشوائيين",
                    ),
                ),
                (
                    "update_interval_seconds",
                    models.IntegerField(
                        default=30,
                        help_text="فترة تحديث عداد الزوار بالثواني",
                        validators=[django.core.validators.MinValueValidator(10)],
                        verbose_name="فترة التحديث (ثانية)",
                    ),
                ),
                (
                    "show_real_visitors",
                    models.BooleanField(
                        default=False,
                        help_text="إظهار عدد الزوار الحقيقي أم العشوائي",
                        verbose_name="إظهار الزوار الحقيقيين",
                    ),
                ),
                (
                    "is_counter_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="هل عداد الزوار مفعل؟",
                        verbose_name="تفعيل العداد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات عداد الزوار",
                "verbose_name_plural": "إعدادات عداد الزوار",
            },
        ),
    ]
