# Generated by Django 4.2.7 on 2025-09-22 20:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsTickerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان الخبر في الشريط الإخباري",
                        max_length=200,
                        verbose_name="عنوان الخبر",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="محتوى تفصيلي للخبر (اختياري)",
                        verbose_name="محتوى الخبر",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="رابط خارجي للخبر (اختياري)",
                        verbose_name="رابط الخبر",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل الخبر نشط في الشريط؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="ترتيب الخبر في الشريط (1 = الأعلى)",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="تاريخ بداية عرض الخبر",
                        verbose_name="تاريخ البداية",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاريخ نهاية عرض الخبر (اختياري)",
                        null=True,
                        verbose_name="تاريخ النهاية",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="الأدمن الذي أنشأ الخبر",
                        max_length=100,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "خبر الشريط الإخباري",
                "verbose_name_plural": "أخبار الشريط الإخباري",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="نائبك.كوم",
                        help_text="اسم الموقع",
                        max_length=100,
                        verbose_name="اسم الموقع",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#22C55E",
                        help_text="اللون الأساسي للموقع (أخضر)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "يجب أن يكون لون hex صحيح"
                            )
                        ],
                        verbose_name="اللون الأساسي",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#F97316",
                        help_text="اللون الثانوي للموقع (برتقالي)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "يجب أن يكون لون hex صحيح"
                            )
                        ],
                        verbose_name="اللون الثانوي",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        help_text="رابط صفحة فيسبوك",
                        verbose_name="رابط فيسبوك",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        help_text="رابط حساب تويتر",
                        verbose_name="رابط تويتر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
